export const SECTIONS = [
  { id: "auto-complete", title: "Auto Complete", group: "Data Entry" },
  { id: "avatar", title: "Avatar", group: "Data Display" },
  { id: "badge", title: "Badge", group: "Data Display" },
  { id: "breadcrumbs", title: "Breadcrumbs", group: "Navigation" },
  { id: "button-dropdown", title: "Button Dropdown", group: "Navigation" },
  { id: "button-group", title: "Button Group", group: "Data Entry" },
  { id: "button", title: "Button", group: "General" },
  { id: "capacity", title: "Capacity", group: "Data Display" },
  { id: "card", title: "Card", group: "Surfaces" },
  { id: "checkbox", title: "Checkbox", group: "Data Entry" },
  { id: "code", title: "Code", group: "General" },
  { id: "collapse", title: "Collapse", group: "Surfaces" },
  { id: "description", title: "Description", group: "Data Display" },
  { id: "display", title: "Display", group: "Data Display" },
  { id: "divider", title: "Divider", group: "Others" },
  { id: "dot", title: "Dot", group: "Data Display" },
  { id: "drawer", title: "Drawer", group: "Feedback" },
  { id: "fieldset", title: "Fieldset", group: "Surfaces" },
  { id: "grid", title: "Grid", group: "Layout" },
  { id: "image", title: "Image", group: "Data Display" },
  { id: "input", title: "Input", group: "Data Entry" },
  { id: "keyboard", title: "Keyboard", group: "Data Display" },
  { id: "link", title: "Link", group: "Navigation" },
  { id: "loading", title: "Loading", group: "Feedback" },
  { id: "modal", title: "Modal", group: "Feedback" },
  { id: "note", title: "Note", group: "Feedback" },
  { id: "page", title: "Page", group: "Layout" },
  { id: "pagination", title: "Pagination", group: "Navigation" },
  { id: "popover", title: "Popover", group: "Data Display" },
  { id: "progress", title: "Progress", group: "Feedback" },
  { id: "radio", title: "Radio", group: "Data Entry" },
  { id: "rating", title: "Rating", group: "Feedback" },
  { id: "select", title: "Select", group: "Data Entry" },
  { id: "slider", title: "Slider", group: "Data Entry" },
  { id: "snippet", title: "Snippet", group: "Others" },
  { id: "spacer", title: "Spacer", group: "Layout" },
  { id: "spinner", title: "Spinner", group: "Feedback" },
  { id: "table", title: "Table", group: "Data Display" },
  { id: "tabs", title: "Tabs", group: "Navigation" },
  { id: "tag", title: "Tag", group: "Data Display" },
  { id: "text", title: "Text", group: "General" },
  { id: "textarea", title: "Textarea", group: "Data Entry" },
  { id: "toggle", title: "Toggle", group: "Data Entry" },
  { id: "tooltip", title: "Tooltip", group: "Data Display" },
  { id: "tree", title: "Tree", group: "Data Display" },
  { id: "user", title: "User", group: "Data Display" },
  { id: "toasts", title: "Toasts", group: "Feedback" },
];

export const GROUP_ORDER = [
  "General",
  "Layout",
  "Data Entry",
  "Data Display",
  "Feedback",
  "Navigation",
  "Surfaces",
  "Others",
];
